/*----- PROTECTED REGION ID(Pico11Class.cpp) ENABLED START -----*/
static const char *RcsId      = "$Id:  $";
static const char *TagName    = "$Name:  $";
static const char *CvsPath    = "$Source:  $";
static const char *SvnPath    = "$HeadURL:  $";
static const char *HttpServer = "http://www.esrf.eu/computing/cs/tango/tango_doc/ds_doc/";
//=============================================================================
//
// file :        Pico11Class.cpp
//
// description : C++ source for the Pico11Class.
//               A singleton class derived from DeviceClass.
//               It implements the command and attribute list
//               and all properties and methods required
//               by the Pico11 once per process.
//
// project :     Pico11
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
// Pico11
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <Pico11Class.h>

/*----- PROTECTED REGION END -----*/	//	Pico11Class.cpp

//-------------------------------------------------------------------
/**
 *	Create Pico11Class singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_Pico11_class(const char *name) {
		return Pico11_ns::Pico11Class::init(name);
	}
}

namespace Pico11_ns
{
//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
Pico11Class *Pico11Class::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		Pico11Class::Pico11Class(string &s)
 * description : 	constructor for the Pico11Class
 *
 * @param s	The class name
 */
//--------------------------------------------------------
Pico11Class::Pico11Class(string &s):Tango::DeviceClass(s)
{
	cout2 << "Entering Pico11Class constructor" << endl;
	set_default_property();
	write_class_property();

	/*----- PROTECTED REGION ID(Pico11Class::constructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Pico11Class::constructor

	cout2 << "Leaving Pico11Class constructor" << endl;
}

//--------------------------------------------------------
/**
 * method : 		Pico11Class::~Pico11Class()
 * description : 	destructor for the Pico11Class
 */
//--------------------------------------------------------
Pico11Class::~Pico11Class()
{
	/*----- PROTECTED REGION ID(Pico11Class::destructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Pico11Class::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		Pico11Class::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
Pico11Class *Pico11Class::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new Pico11Class(s);
		}
		catch (bad_alloc &)
		{
			throw;
		}
	}
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		Pico11Class::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
Pico11Class *Pico11Class::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}



//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		SetDefaultsClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *SetDefaultsClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "SetDefaultsClass::execute(): arrived" << endl;
	((static_cast<Pico11 *>(device))->set_defaults());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		StartStreamingClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *StartStreamingClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "StartStreamingClass::execute(): arrived" << endl;
	((static_cast<Pico11 *>(device))->start_streaming());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		StopStreamingClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *StopStreamingClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "StopStreamingClass::execute(): arrived" << endl;
	((static_cast<Pico11 *>(device))->stop_streaming());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		UpdateClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *UpdateClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "UpdateClass::execute(): arrived" << endl;
	((static_cast<Pico11 *>(device))->update());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		OnClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *OnClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "OnClass::execute(): arrived" << endl;
	((static_cast<Pico11 *>(device))->on());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		OffClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *OffClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "OffClass::execute(): arrived" << endl;
	((static_cast<Pico11 *>(device))->off());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		CollectBlockClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *CollectBlockClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "CollectBlockClass::execute(): arrived" << endl;
	((static_cast<Pico11 *>(device))->collect_block());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		SetTrigParamAClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *SetTrigParamAClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "SetTrigParamAClass::execute(): arrived" << endl;
	((static_cast<Pico11 *>(device))->set_trig_param_a());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		SetTrigParamBClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *SetTrigParamBClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "SetTrigParamBClass::execute(): arrived" << endl;
	((static_cast<Pico11 *>(device))->set_trig_param_b());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		SetTrigParamCClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *SetTrigParamCClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "SetTrigParamCClass::execute(): arrived" << endl;
	((static_cast<Pico11 *>(device))->set_trig_param_c());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		SetTrigParamDClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *SetTrigParamDClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "SetTrigParamDClass::execute(): arrived" << endl;
	((static_cast<Pico11 *>(device))->set_trig_param_d());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		CollectBlockEtsClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *CollectBlockEtsClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "CollectBlockEtsClass::execute(): arrived" << endl;
	((static_cast<Pico11 *>(device))->collect_block_ets());
	return new CORBA::Any();
}


//===================================================================
//	Properties management
//===================================================================
//--------------------------------------------------------
/**
 *	Method      : Pico11Class::get_class_property()
 *	Description : Get the class property for specified name.
 */
//--------------------------------------------------------
Tango::DbDatum Pico11Class::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : Pico11Class::get_default_device_property()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum Pico11Class::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : Pico11Class::get_default_class_property()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum Pico11Class::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : Pico11Class::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *                For each property, add to wizard property name and description.
 *                If default value has been set, add it to wizard property and
 *                store it in a DbDatum.
 */
//--------------------------------------------------------
void Pico11Class::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;

	//	Set Default Class Properties

	//	Set Default device Properties
}

//--------------------------------------------------------
/**
 *	Method      : Pico11Class::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void Pico11Class::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("Pico11");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("Pico11");
	description << str_desc;
	data.push_back(description);

	//	put cvs or svn location
	string	filename("Pico11");
	filename += "Class.cpp";

	// check for cvs information
	string	src_path(CvsPath);
	start = src_path.find("/");
	if (start!=string::npos)
	{
		end   = src_path.find(filename);
		if (end>start)
		{
			string	strloc = src_path.substr(start, end-start);
			//	Check if specific repository
			start = strloc.find("/cvsroot/");
			if (start!=string::npos && start>0)
			{
				string	repository = strloc.substr(0, start);
				if (repository.find("/segfs/")!=string::npos)
					strloc = "ESRF:" + strloc.substr(start, strloc.length()-start);
			}
			Tango::DbDatum	cvs_loc("cvs_location");
			cvs_loc << strloc;
			data.push_back(cvs_loc);
		}
	}

	// check for svn information
	else
	{
		string	src_path(SvnPath);
		start = src_path.find("://");
		if (start!=string::npos)
		{
			end = src_path.find(filename);
			if (end>start)
			{
				header = "$HeadURL: ";
				start = header.length();
				string	strloc = src_path.substr(start, (end-start));
				
				Tango::DbDatum	svn_loc("svn_location");
				svn_loc << strloc;
				data.push_back(svn_loc);
			}
		}
	}

	//	Get CVS or SVN revision tag
	
	// CVS tag
	string	tagname(TagName);
	header = "$Name: ";
	start = header.length();
	string	endstr(" $");
	
	end   = tagname.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strtag = tagname.substr(start, end-start);
		Tango::DbDatum	cvs_tag("cvs_tag");
		cvs_tag << strtag;
		data.push_back(cvs_tag);
	}
	
	// SVN tag
	string	svnpath(SvnPath);
	header = "$HeadURL: ";
	start = header.length();
	
	end   = svnpath.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strloc = svnpath.substr(start, end-start);
		
		string tagstr ("/tags/");
		start = strloc.find(tagstr);
		if ( start!=string::npos )
		{
			start = start + tagstr.length();
			end   = strloc.find(filename);
			string	strtag = strloc.substr(start, end-start-1);
			
			Tango::DbDatum	svn_tag("svn_tag");
			svn_tag << strtag;
			data.push_back(svn_tag);
		}
	}

	//	Get URL location
	string	httpServ(HttpServer);
	if (httpServ.length()>0)
	{
		Tango::DbDatum	db_doc_url("doc_url");
		db_doc_url << httpServ;
		data.push_back(db_doc_url);
	}

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("TANGO_BASE_CLASS");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}

//===================================================================
//	Factory methods
//===================================================================

//--------------------------------------------------------
/**
 *	Method      : Pico11Class::device_factory()
 *	Description : Create the device object(s)
 *                and store them in the device list
 */
//--------------------------------------------------------
void Pico11Class::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{
	/*----- PROTECTED REGION ID(Pico11Class::device_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	Pico11Class::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new Pico11(this, (*devlist_ptr)[i]));
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		Pico11 *dev = static_cast<Pico11 *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(Pico11Class::device_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	Pico11Class::device_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : Pico11Class::attribute_factory()
 *	Description : Create the attribute object(s)
 *                and store them in the attribute list
 */
//--------------------------------------------------------
void Pico11Class::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(Pico11Class::attribute_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	Pico11Class::attribute_factory_before
	//	Attribute : chanAstream
	chanAstreamAttrib	*chanastream = new chanAstreamAttrib();
	Tango::UserDefaultAttrProp	chanastream_prop;
	//	description	not set for chanAstream
	//	label	not set for chanAstream
	//	unit	not set for chanAstream
	//	standard_unit	not set for chanAstream
	//	display_unit	not set for chanAstream
	//	format	not set for chanAstream
	//	max_value	not set for chanAstream
	//	min_value	not set for chanAstream
	//	max_alarm	not set for chanAstream
	//	min_alarm	not set for chanAstream
	//	max_warning	not set for chanAstream
	//	min_warning	not set for chanAstream
	//	delta_t	not set for chanAstream
	//	delta_val	not set for chanAstream
	
	chanastream->set_default_properties(chanastream_prop);
	//	Not Polled
	chanastream->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(chanastream);

	//	Attribute : DevChoose
	DevChooseAttrib	*devchoose = new DevChooseAttrib();
	Tango::UserDefaultAttrProp	devchoose_prop;
	//	description	not set for DevChoose
	//	label	not set for DevChoose
	//	unit	not set for DevChoose
	//	standard_unit	not set for DevChoose
	//	display_unit	not set for DevChoose
	//	format	not set for DevChoose
	//	max_value	not set for DevChoose
	//	min_value	not set for DevChoose
	//	max_alarm	not set for DevChoose
	//	min_alarm	not set for DevChoose
	//	max_warning	not set for DevChoose
	//	min_warning	not set for DevChoose
	//	delta_t	not set for DevChoose
	//	delta_val	not set for DevChoose
	
	devchoose->set_default_properties(devchoose_prop);
	//	Not Polled
	devchoose->set_disp_level(Tango::OPERATOR);
	devchoose->set_memorized();
	devchoose->set_memorized_init(false);
	att_list.push_back(devchoose);

	//	Attribute : DevCh
	DevChAttrib	*devch = new DevChAttrib();
	Tango::UserDefaultAttrProp	devch_prop;
	//	description	not set for DevCh
	//	label	not set for DevCh
	//	unit	not set for DevCh
	//	standard_unit	not set for DevCh
	//	display_unit	not set for DevCh
	//	format	not set for DevCh
	//	max_value	not set for DevCh
	//	min_value	not set for DevCh
	//	max_alarm	not set for DevCh
	//	min_alarm	not set for DevCh
	//	max_warning	not set for DevCh
	//	min_warning	not set for DevCh
	//	delta_t	not set for DevCh
	//	delta_val	not set for DevCh
	
	devch->set_default_properties(devch_prop);
	//	Not Polled
	devch->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(devch);

	//	Attribute : TrgCh
	TrgChAttrib	*trgch = new TrgChAttrib();
	Tango::UserDefaultAttrProp	trgch_prop;
	//	description	not set for TrgCh
	//	label	not set for TrgCh
	//	unit	not set for TrgCh
	//	standard_unit	not set for TrgCh
	//	display_unit	not set for TrgCh
	//	format	not set for TrgCh
	//	max_value	not set for TrgCh
	//	min_value	not set for TrgCh
	//	max_alarm	not set for TrgCh
	//	min_alarm	not set for TrgCh
	//	max_warning	not set for TrgCh
	//	min_warning	not set for TrgCh
	//	delta_t	not set for TrgCh
	//	delta_val	not set for TrgCh
	
	trgch->set_default_properties(trgch_prop);
	//	Not Polled
	trgch->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(trgch);

	//	Attribute : DevChooseStr
	DevChooseStrAttrib	*devchoosestr = new DevChooseStrAttrib();
	Tango::UserDefaultAttrProp	devchoosestr_prop;
	//	description	not set for DevChooseStr
	//	label	not set for DevChooseStr
	//	unit	not set for DevChooseStr
	//	standard_unit	not set for DevChooseStr
	//	display_unit	not set for DevChooseStr
	//	format	not set for DevChooseStr
	//	max_value	not set for DevChooseStr
	//	min_value	not set for DevChooseStr
	//	max_alarm	not set for DevChooseStr
	//	min_alarm	not set for DevChooseStr
	//	max_warning	not set for DevChooseStr
	//	min_warning	not set for DevChooseStr
	//	delta_t	not set for DevChooseStr
	//	delta_val	not set for DevChooseStr
	
	devchoosestr->set_default_properties(devchoosestr_prop);
	//	Not Polled
	devchoosestr->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(devchoosestr);

	//	Attribute : ThresholdUp
	ThresholdUpAttrib	*thresholdup = new ThresholdUpAttrib();
	Tango::UserDefaultAttrProp	thresholdup_prop;
	//	description	not set for ThresholdUp
	//	label	not set for ThresholdUp
	//	unit	not set for ThresholdUp
	//	standard_unit	not set for ThresholdUp
	//	display_unit	not set for ThresholdUp
	//	format	not set for ThresholdUp
	//	max_value	not set for ThresholdUp
	//	min_value	not set for ThresholdUp
	//	max_alarm	not set for ThresholdUp
	//	min_alarm	not set for ThresholdUp
	//	max_warning	not set for ThresholdUp
	//	min_warning	not set for ThresholdUp
	//	delta_t	not set for ThresholdUp
	//	delta_val	not set for ThresholdUp
	
	thresholdup->set_default_properties(thresholdup_prop);
	//	Not Polled
	thresholdup->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(thresholdup);

	//	Attribute : ThresholdLo
	ThresholdLoAttrib	*thresholdlo = new ThresholdLoAttrib();
	Tango::UserDefaultAttrProp	thresholdlo_prop;
	//	description	not set for ThresholdLo
	//	label	not set for ThresholdLo
	//	unit	not set for ThresholdLo
	//	standard_unit	not set for ThresholdLo
	//	display_unit	not set for ThresholdLo
	//	format	not set for ThresholdLo
	//	max_value	not set for ThresholdLo
	//	min_value	not set for ThresholdLo
	//	max_alarm	not set for ThresholdLo
	//	min_alarm	not set for ThresholdLo
	//	max_warning	not set for ThresholdLo
	//	min_warning	not set for ThresholdLo
	//	delta_t	not set for ThresholdLo
	//	delta_val	not set for ThresholdLo
	
	thresholdlo->set_default_properties(thresholdlo_prop);
	//	Not Polled
	thresholdlo->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(thresholdlo);

	//	Attribute : HysteresisUp
	HysteresisUpAttrib	*hysteresisup = new HysteresisUpAttrib();
	Tango::UserDefaultAttrProp	hysteresisup_prop;
	//	description	not set for HysteresisUp
	//	label	not set for HysteresisUp
	//	unit	not set for HysteresisUp
	//	standard_unit	not set for HysteresisUp
	//	display_unit	not set for HysteresisUp
	//	format	not set for HysteresisUp
	//	max_value	not set for HysteresisUp
	//	min_value	not set for HysteresisUp
	//	max_alarm	not set for HysteresisUp
	//	min_alarm	not set for HysteresisUp
	//	max_warning	not set for HysteresisUp
	//	min_warning	not set for HysteresisUp
	//	delta_t	not set for HysteresisUp
	//	delta_val	not set for HysteresisUp
	
	hysteresisup->set_default_properties(hysteresisup_prop);
	//	Not Polled
	hysteresisup->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(hysteresisup);

	//	Attribute : HysteresisLo
	HysteresisLoAttrib	*hysteresislo = new HysteresisLoAttrib();
	Tango::UserDefaultAttrProp	hysteresislo_prop;
	//	description	not set for HysteresisLo
	//	label	not set for HysteresisLo
	//	unit	not set for HysteresisLo
	//	standard_unit	not set for HysteresisLo
	//	display_unit	not set for HysteresisLo
	//	format	not set for HysteresisLo
	//	max_value	not set for HysteresisLo
	//	min_value	not set for HysteresisLo
	//	max_alarm	not set for HysteresisLo
	//	min_alarm	not set for HysteresisLo
	//	max_warning	not set for HysteresisLo
	//	min_warning	not set for HysteresisLo
	//	delta_t	not set for HysteresisLo
	//	delta_val	not set for HysteresisLo
	
	hysteresislo->set_default_properties(hysteresislo_prop);
	//	Not Polled
	hysteresislo->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(hysteresislo);

	//	Attribute : ThresholdMode
	ThresholdModeAttrib	*thresholdmode = new ThresholdModeAttrib();
	Tango::UserDefaultAttrProp	thresholdmode_prop;
	//	description	not set for ThresholdMode
	//	label	not set for ThresholdMode
	//	unit	not set for ThresholdMode
	//	standard_unit	not set for ThresholdMode
	//	display_unit	not set for ThresholdMode
	//	format	not set for ThresholdMode
	//	max_value	not set for ThresholdMode
	//	min_value	not set for ThresholdMode
	//	max_alarm	not set for ThresholdMode
	//	min_alarm	not set for ThresholdMode
	//	max_warning	not set for ThresholdMode
	//	min_warning	not set for ThresholdMode
	//	delta_t	not set for ThresholdMode
	//	delta_val	not set for ThresholdMode
	
	thresholdmode->set_default_properties(thresholdmode_prop);
	//	Not Polled
	thresholdmode->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(thresholdmode);

	//	Attribute : ChanACond
	ChanACondAttrib	*chanacond = new ChanACondAttrib();
	Tango::UserDefaultAttrProp	chanacond_prop;
	//	description	not set for ChanACond
	//	label	not set for ChanACond
	//	unit	not set for ChanACond
	//	standard_unit	not set for ChanACond
	//	display_unit	not set for ChanACond
	//	format	not set for ChanACond
	//	max_value	not set for ChanACond
	//	min_value	not set for ChanACond
	//	max_alarm	not set for ChanACond
	//	min_alarm	not set for ChanACond
	//	max_warning	not set for ChanACond
	//	min_warning	not set for ChanACond
	//	delta_t	not set for ChanACond
	//	delta_val	not set for ChanACond
	
	chanacond->set_default_properties(chanacond_prop);
	//	Not Polled
	chanacond->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(chanacond);

	//	Attribute : ChanBCond
	ChanBCondAttrib	*chanbcond = new ChanBCondAttrib();
	Tango::UserDefaultAttrProp	chanbcond_prop;
	//	description	not set for ChanBCond
	//	label	not set for ChanBCond
	//	unit	not set for ChanBCond
	//	standard_unit	not set for ChanBCond
	//	display_unit	not set for ChanBCond
	//	format	not set for ChanBCond
	//	max_value	not set for ChanBCond
	//	min_value	not set for ChanBCond
	//	max_alarm	not set for ChanBCond
	//	min_alarm	not set for ChanBCond
	//	max_warning	not set for ChanBCond
	//	min_warning	not set for ChanBCond
	//	delta_t	not set for ChanBCond
	//	delta_val	not set for ChanBCond
	
	chanbcond->set_default_properties(chanbcond_prop);
	//	Not Polled
	chanbcond->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(chanbcond);

	//	Attribute : ChanCCond
	ChanCCondAttrib	*chanccond = new ChanCCondAttrib();
	Tango::UserDefaultAttrProp	chanccond_prop;
	//	description	not set for ChanCCond
	//	label	not set for ChanCCond
	//	unit	not set for ChanCCond
	//	standard_unit	not set for ChanCCond
	//	display_unit	not set for ChanCCond
	//	format	not set for ChanCCond
	//	max_value	not set for ChanCCond
	//	min_value	not set for ChanCCond
	//	max_alarm	not set for ChanCCond
	//	min_alarm	not set for ChanCCond
	//	max_warning	not set for ChanCCond
	//	min_warning	not set for ChanCCond
	//	delta_t	not set for ChanCCond
	//	delta_val	not set for ChanCCond
	
	chanccond->set_default_properties(chanccond_prop);
	//	Not Polled
	chanccond->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(chanccond);

	//	Attribute : ChanDCond
	ChanDCondAttrib	*chandcond = new ChanDCondAttrib();
	Tango::UserDefaultAttrProp	chandcond_prop;
	//	description	not set for ChanDCond
	//	label	not set for ChanDCond
	//	unit	not set for ChanDCond
	//	standard_unit	not set for ChanDCond
	//	display_unit	not set for ChanDCond
	//	format	not set for ChanDCond
	//	max_value	not set for ChanDCond
	//	min_value	not set for ChanDCond
	//	max_alarm	not set for ChanDCond
	//	min_alarm	not set for ChanDCond
	//	max_warning	not set for ChanDCond
	//	min_warning	not set for ChanDCond
	//	delta_t	not set for ChanDCond
	//	delta_val	not set for ChanDCond
	
	chandcond->set_default_properties(chandcond_prop);
	//	Not Polled
	chandcond->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(chandcond);

	//	Attribute : ChanAuxCond
	ChanAuxCondAttrib	*chanauxcond = new ChanAuxCondAttrib();
	Tango::UserDefaultAttrProp	chanauxcond_prop;
	//	description	not set for ChanAuxCond
	//	label	not set for ChanAuxCond
	//	unit	not set for ChanAuxCond
	//	standard_unit	not set for ChanAuxCond
	//	display_unit	not set for ChanAuxCond
	//	format	not set for ChanAuxCond
	//	max_value	not set for ChanAuxCond
	//	min_value	not set for ChanAuxCond
	//	max_alarm	not set for ChanAuxCond
	//	min_alarm	not set for ChanAuxCond
	//	max_warning	not set for ChanAuxCond
	//	min_warning	not set for ChanAuxCond
	//	delta_t	not set for ChanAuxCond
	//	delta_val	not set for ChanAuxCond
	
	chanauxcond->set_default_properties(chanauxcond_prop);
	//	Not Polled
	chanauxcond->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(chanauxcond);

	//	Attribute : ChanPwqCond
	ChanPwqCondAttrib	*chanpwqcond = new ChanPwqCondAttrib();
	Tango::UserDefaultAttrProp	chanpwqcond_prop;
	//	description	not set for ChanPwqCond
	//	label	not set for ChanPwqCond
	//	unit	not set for ChanPwqCond
	//	standard_unit	not set for ChanPwqCond
	//	display_unit	not set for ChanPwqCond
	//	format	not set for ChanPwqCond
	//	max_value	not set for ChanPwqCond
	//	min_value	not set for ChanPwqCond
	//	max_alarm	not set for ChanPwqCond
	//	min_alarm	not set for ChanPwqCond
	//	max_warning	not set for ChanPwqCond
	//	min_warning	not set for ChanPwqCond
	//	delta_t	not set for ChanPwqCond
	//	delta_val	not set for ChanPwqCond
	
	chanpwqcond->set_default_properties(chanpwqcond_prop);
	//	Not Polled
	chanpwqcond->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(chanpwqcond);

	//	Attribute : ChanExtCond
	ChanExtCondAttrib	*chanextcond = new ChanExtCondAttrib();
	Tango::UserDefaultAttrProp	chanextcond_prop;
	//	description	not set for ChanExtCond
	//	label	not set for ChanExtCond
	//	unit	not set for ChanExtCond
	//	standard_unit	not set for ChanExtCond
	//	display_unit	not set for ChanExtCond
	//	format	not set for ChanExtCond
	//	max_value	not set for ChanExtCond
	//	min_value	not set for ChanExtCond
	//	max_alarm	not set for ChanExtCond
	//	min_alarm	not set for ChanExtCond
	//	max_warning	not set for ChanExtCond
	//	min_warning	not set for ChanExtCond
	//	delta_t	not set for ChanExtCond
	//	delta_val	not set for ChanExtCond
	
	chanextcond->set_default_properties(chanextcond_prop);
	//	Not Polled
	chanextcond->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(chanextcond);

	//	Attribute : ChanATrigDir
	ChanATrigDirAttrib	*chanatrigdir = new ChanATrigDirAttrib();
	Tango::UserDefaultAttrProp	chanatrigdir_prop;
	//	description	not set for ChanATrigDir
	//	label	not set for ChanATrigDir
	//	unit	not set for ChanATrigDir
	//	standard_unit	not set for ChanATrigDir
	//	display_unit	not set for ChanATrigDir
	//	format	not set for ChanATrigDir
	//	max_value	not set for ChanATrigDir
	//	min_value	not set for ChanATrigDir
	//	max_alarm	not set for ChanATrigDir
	//	min_alarm	not set for ChanATrigDir
	//	max_warning	not set for ChanATrigDir
	//	min_warning	not set for ChanATrigDir
	//	delta_t	not set for ChanATrigDir
	//	delta_val	not set for ChanATrigDir
	
	chanatrigdir->set_default_properties(chanatrigdir_prop);
	//	Not Polled
	chanatrigdir->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(chanatrigdir);

	//	Attribute : ChanBTrigDir
	ChanBTrigDirAttrib	*chanbtrigdir = new ChanBTrigDirAttrib();
	Tango::UserDefaultAttrProp	chanbtrigdir_prop;
	//	description	not set for ChanBTrigDir
	//	label	not set for ChanBTrigDir
	//	unit	not set for ChanBTrigDir
	//	standard_unit	not set for ChanBTrigDir
	//	display_unit	not set for ChanBTrigDir
	//	format	not set for ChanBTrigDir
	//	max_value	not set for ChanBTrigDir
	//	min_value	not set for ChanBTrigDir
	//	max_alarm	not set for ChanBTrigDir
	//	min_alarm	not set for ChanBTrigDir
	//	max_warning	not set for ChanBTrigDir
	//	min_warning	not set for ChanBTrigDir
	//	delta_t	not set for ChanBTrigDir
	//	delta_val	not set for ChanBTrigDir
	
	chanbtrigdir->set_default_properties(chanbtrigdir_prop);
	//	Not Polled
	chanbtrigdir->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(chanbtrigdir);

	//	Attribute : ChanCTrigDir
	ChanCTrigDirAttrib	*chanctrigdir = new ChanCTrigDirAttrib();
	Tango::UserDefaultAttrProp	chanctrigdir_prop;
	//	description	not set for ChanCTrigDir
	//	label	not set for ChanCTrigDir
	//	unit	not set for ChanCTrigDir
	//	standard_unit	not set for ChanCTrigDir
	//	display_unit	not set for ChanCTrigDir
	//	format	not set for ChanCTrigDir
	//	max_value	not set for ChanCTrigDir
	//	min_value	not set for ChanCTrigDir
	//	max_alarm	not set for ChanCTrigDir
	//	min_alarm	not set for ChanCTrigDir
	//	max_warning	not set for ChanCTrigDir
	//	min_warning	not set for ChanCTrigDir
	//	delta_t	not set for ChanCTrigDir
	//	delta_val	not set for ChanCTrigDir
	
	chanctrigdir->set_default_properties(chanctrigdir_prop);
	//	Not Polled
	chanctrigdir->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(chanctrigdir);

	//	Attribute : ChanDTrigDir
	ChanDTrigDirAttrib	*chandtrigdir = new ChanDTrigDirAttrib();
	Tango::UserDefaultAttrProp	chandtrigdir_prop;
	//	description	not set for ChanDTrigDir
	//	label	not set for ChanDTrigDir
	//	unit	not set for ChanDTrigDir
	//	standard_unit	not set for ChanDTrigDir
	//	display_unit	not set for ChanDTrigDir
	//	format	not set for ChanDTrigDir
	//	max_value	not set for ChanDTrigDir
	//	min_value	not set for ChanDTrigDir
	//	max_alarm	not set for ChanDTrigDir
	//	min_alarm	not set for ChanDTrigDir
	//	max_warning	not set for ChanDTrigDir
	//	min_warning	not set for ChanDTrigDir
	//	delta_t	not set for ChanDTrigDir
	//	delta_val	not set for ChanDTrigDir
	
	chandtrigdir->set_default_properties(chandtrigdir_prop);
	//	Not Polled
	chandtrigdir->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(chandtrigdir);

	//	Attribute : ChanAuxTrigDir
	ChanAuxTrigDirAttrib	*chanauxtrigdir = new ChanAuxTrigDirAttrib();
	Tango::UserDefaultAttrProp	chanauxtrigdir_prop;
	//	description	not set for ChanAuxTrigDir
	//	label	not set for ChanAuxTrigDir
	//	unit	not set for ChanAuxTrigDir
	//	standard_unit	not set for ChanAuxTrigDir
	//	display_unit	not set for ChanAuxTrigDir
	//	format	not set for ChanAuxTrigDir
	//	max_value	not set for ChanAuxTrigDir
	//	min_value	not set for ChanAuxTrigDir
	//	max_alarm	not set for ChanAuxTrigDir
	//	min_alarm	not set for ChanAuxTrigDir
	//	max_warning	not set for ChanAuxTrigDir
	//	min_warning	not set for ChanAuxTrigDir
	//	delta_t	not set for ChanAuxTrigDir
	//	delta_val	not set for ChanAuxTrigDir
	
	chanauxtrigdir->set_default_properties(chanauxtrigdir_prop);
	//	Not Polled
	chanauxtrigdir->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(chanauxtrigdir);

	//	Attribute : ChanExtTrigDir
	ChanExtTrigDirAttrib	*chanexttrigdir = new ChanExtTrigDirAttrib();
	Tango::UserDefaultAttrProp	chanexttrigdir_prop;
	//	description	not set for ChanExtTrigDir
	//	label	not set for ChanExtTrigDir
	//	unit	not set for ChanExtTrigDir
	//	standard_unit	not set for ChanExtTrigDir
	//	display_unit	not set for ChanExtTrigDir
	//	format	not set for ChanExtTrigDir
	//	max_value	not set for ChanExtTrigDir
	//	min_value	not set for ChanExtTrigDir
	//	max_alarm	not set for ChanExtTrigDir
	//	min_alarm	not set for ChanExtTrigDir
	//	max_warning	not set for ChanExtTrigDir
	//	min_warning	not set for ChanExtTrigDir
	//	delta_t	not set for ChanExtTrigDir
	//	delta_val	not set for ChanExtTrigDir
	
	chanexttrigdir->set_default_properties(chanexttrigdir_prop);
	//	Not Polled
	chanexttrigdir->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(chanexttrigdir);

	//	Attribute : TrigDelay
	TrigDelayAttrib	*trigdelay = new TrigDelayAttrib();
	Tango::UserDefaultAttrProp	trigdelay_prop;
	//	description	not set for TrigDelay
	//	label	not set for TrigDelay
	//	unit	not set for TrigDelay
	//	standard_unit	not set for TrigDelay
	//	display_unit	not set for TrigDelay
	//	format	not set for TrigDelay
	//	max_value	not set for TrigDelay
	//	min_value	not set for TrigDelay
	//	max_alarm	not set for TrigDelay
	//	min_alarm	not set for TrigDelay
	//	max_warning	not set for TrigDelay
	//	min_warning	not set for TrigDelay
	//	delta_t	not set for TrigDelay
	//	delta_val	not set for TrigDelay
	
	trigdelay->set_default_properties(trigdelay_prop);
	//	Not Polled
	trigdelay->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(trigdelay);

	//	Attribute : chanA
	chanAAttrib	*chana = new chanAAttrib();
	Tango::UserDefaultAttrProp	chana_prop;
	//	description	not set for chanA
	//	label	not set for chanA
	//	unit	not set for chanA
	//	standard_unit	not set for chanA
	//	display_unit	not set for chanA
	//	format	not set for chanA
	//	max_value	not set for chanA
	//	min_value	not set for chanA
	//	max_alarm	not set for chanA
	//	min_alarm	not set for chanA
	//	max_warning	not set for chanA
	//	min_warning	not set for chanA
	//	delta_t	not set for chanA
	//	delta_val	not set for chanA
	
	chana->set_default_properties(chana_prop);
	//	Not Polled
	chana->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(chana);

	//	Attribute : chanB
	chanBAttrib	*chanb = new chanBAttrib();
	Tango::UserDefaultAttrProp	chanb_prop;
	//	description	not set for chanB
	//	label	not set for chanB
	//	unit	not set for chanB
	//	standard_unit	not set for chanB
	//	display_unit	not set for chanB
	//	format	not set for chanB
	//	max_value	not set for chanB
	//	min_value	not set for chanB
	//	max_alarm	not set for chanB
	//	min_alarm	not set for chanB
	//	max_warning	not set for chanB
	//	min_warning	not set for chanB
	//	delta_t	not set for chanB
	//	delta_val	not set for chanB
	
	chanb->set_default_properties(chanb_prop);
	//	Not Polled
	chanb->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(chanb);

	//	Attribute : chanC
	chanCAttrib	*chanc = new chanCAttrib();
	Tango::UserDefaultAttrProp	chanc_prop;
	//	description	not set for chanC
	//	label	not set for chanC
	//	unit	not set for chanC
	//	standard_unit	not set for chanC
	//	display_unit	not set for chanC
	//	format	not set for chanC
	//	max_value	not set for chanC
	//	min_value	not set for chanC
	//	max_alarm	not set for chanC
	//	min_alarm	not set for chanC
	//	max_warning	not set for chanC
	//	min_warning	not set for chanC
	//	delta_t	not set for chanC
	//	delta_val	not set for chanC
	
	chanc->set_default_properties(chanc_prop);
	//	Not Polled
	chanc->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(chanc);

	//	Attribute : chanD
	chanDAttrib	*chand = new chanDAttrib();
	Tango::UserDefaultAttrProp	chand_prop;
	//	description	not set for chanD
	//	label	not set for chanD
	//	unit	not set for chanD
	//	standard_unit	not set for chanD
	//	display_unit	not set for chanD
	//	format	not set for chanD
	//	max_value	not set for chanD
	//	min_value	not set for chanD
	//	max_alarm	not set for chanD
	//	min_alarm	not set for chanD
	//	max_warning	not set for chanD
	//	min_warning	not set for chanD
	//	delta_t	not set for chanD
	//	delta_val	not set for chanD
	
	chand->set_default_properties(chand_prop);
	//	Not Polled
	chand->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(chand);


	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());
	/*----- PROTECTED REGION ID(Pico11Class::attribute_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	Pico11Class::attribute_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : Pico11Class::pipe_factory()
 *	Description : Create the pipe object(s)
 *                and store them in the pipe list
 */
//--------------------------------------------------------
void Pico11Class::pipe_factory()
{
	/*----- PROTECTED REGION ID(Pico11Class::pipe_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	Pico11Class::pipe_factory_before
	/*----- PROTECTED REGION ID(Pico11Class::pipe_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	Pico11Class::pipe_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : Pico11Class::command_factory()
 *	Description : Create the command object(s)
 *                and store them in the command list
 */
//--------------------------------------------------------
void Pico11Class::command_factory()
{
	/*----- PROTECTED REGION ID(Pico11Class::command_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	Pico11Class::command_factory_before


	//	Command SetDefaults
	SetDefaultsClass	*pSetDefaultsCmd =
		new SetDefaultsClass("SetDefaults",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pSetDefaultsCmd);

	//	Command StartStreaming
	StartStreamingClass	*pStartStreamingCmd =
		new StartStreamingClass("StartStreaming",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pStartStreamingCmd);

	//	Command StopStreaming
	StopStreamingClass	*pStopStreamingCmd =
		new StopStreamingClass("StopStreaming",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pStopStreamingCmd);

	//	Command Update
	UpdateClass	*pUpdateCmd =
		new UpdateClass("Update",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	pUpdateCmd->set_polling_period(100);
	command_list.push_back(pUpdateCmd);

	//	Command On
	OnClass	*pOnCmd =
		new OnClass("On",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pOnCmd);

	//	Command Off
	OffClass	*pOffCmd =
		new OffClass("Off",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pOffCmd);

	//	Command CollectBlock
	CollectBlockClass	*pCollectBlockCmd =
		new CollectBlockClass("CollectBlock",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pCollectBlockCmd);

	//	Command SetTrigParamA
	SetTrigParamAClass	*pSetTrigParamACmd =
		new SetTrigParamAClass("SetTrigParamA",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pSetTrigParamACmd);

	//	Command SetTrigParamB
	SetTrigParamBClass	*pSetTrigParamBCmd =
		new SetTrigParamBClass("SetTrigParamB",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pSetTrigParamBCmd);

	//	Command SetTrigParamC
	SetTrigParamCClass	*pSetTrigParamCCmd =
		new SetTrigParamCClass("SetTrigParamC",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pSetTrigParamCCmd);

	//	Command SetTrigParamD
	SetTrigParamDClass	*pSetTrigParamDCmd =
		new SetTrigParamDClass("SetTrigParamD",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pSetTrigParamDCmd);

	//	Command CollectBlockEts
	CollectBlockEtsClass	*pCollectBlockEtsCmd =
		new CollectBlockEtsClass("CollectBlockEts",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pCollectBlockEtsCmd);

	/*----- PROTECTED REGION ID(Pico11Class::command_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	Pico11Class::command_factory_after
}

//===================================================================
//	Dynamic attributes related methods
//===================================================================

//--------------------------------------------------------
/**
 * method : 		Pico11Class::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list
 */
//--------------------------------------------------------
void Pico11Class::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;

	/*----- PROTECTED REGION ID(Pico11Class::create_static_att_list) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Pico11Class::create_static_att_list
}


//--------------------------------------------------------
/**
 * method : 		Pico11Class::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void Pico11Class::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		Pico11 *dev = static_cast<Pico11 *> (dev_impl);

		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()], true, false);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(Pico11Class::erase_dynamic_attributes) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Pico11Class::erase_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : Pico11Class::get_attr_by_name()
 *	Description : returns Tango::Attr * object found by name
 */
//--------------------------------------------------------
Tango::Attr *Pico11Class::get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname)
{
	vector<Tango::Attr *>::iterator it;
	for (it=att_list.begin() ; it<att_list.end() ; ++it)
		if ((*it)->get_name()==attname)
			return (*it);
	//	Attr does not exist
	return NULL;
}


/*----- PROTECTED REGION ID(Pico11Class::Additional Methods) ENABLED START -----*/

/*----- PROTECTED REGION END -----*/	//	Pico11Class::Additional Methods
} //	namespace
