/*----- PROTECTED REGION ID(Pico11StateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        Pico11StateMachine.cpp
//
// description : State machine file for the Pico11 class
//
// project :     Pico11
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
// Pico11
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <Pico11.h>

/*----- PROTECTED REGION END -----*/	//	Pico11::Pico11StateMachine.cpp

//================================================================
//  States   |  Description
//================================================================
//  ON       |  
//  OFF      |  
//  FAULT    |  
//  RUNNING  |  


namespace Pico11_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : Pico11::is_chanAstream_allowed()
 *	Description : Execution allowed for chanAstream attribute
 */
//--------------------------------------------------------
bool Pico11::is_chanAstream_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for chanAstream attribute in read access.
	/*----- PROTECTED REGION ID(Pico11::chanAstreamStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Pico11::chanAstreamStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Pico11::is_DevChoose_allowed()
 *	Description : Execution allowed for DevChoose attribute
 */
//--------------------------------------------------------
bool Pico11::is_DevChoose_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for DevChoose attribute in Write access.
	/*----- PROTECTED REGION ID(Pico11::DevChooseStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Pico11::DevChooseStateAllowed_WRITE

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Pico11::is_DevCh_allowed()
 *	Description : Execution allowed for DevCh attribute
 */
//--------------------------------------------------------
bool Pico11::is_DevCh_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for DevCh attribute in read access.
	/*----- PROTECTED REGION ID(Pico11::DevChStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Pico11::DevChStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Pico11::is_chanA_allowed()
 *	Description : Execution allowed for chanA attribute
 */
//--------------------------------------------------------
bool Pico11::is_chanA_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for chanA attribute in read access.
	/*----- PROTECTED REGION ID(Pico11::chanAStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Pico11::chanAStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Pico11::is_chanB_allowed()
 *	Description : Execution allowed for chanB attribute
 */
//--------------------------------------------------------
bool Pico11::is_chanB_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for chanB attribute in read access.
	/*----- PROTECTED REGION ID(Pico11::chanBStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Pico11::chanBStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Pico11::is_chanC_allowed()
 *	Description : Execution allowed for chanC attribute
 */
//--------------------------------------------------------
bool Pico11::is_chanC_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for chanC attribute in read access.
	/*----- PROTECTED REGION ID(Pico11::chanCStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Pico11::chanCStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Pico11::is_chanD_allowed()
 *	Description : Execution allowed for chanD attribute
 */
//--------------------------------------------------------
bool Pico11::is_chanD_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for chanD attribute in read access.
	/*----- PROTECTED REGION ID(Pico11::chanDStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Pico11::chanDStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : Pico11::is_SetDefaults_allowed()
 *	Description : Execution allowed for SetDefaults attribute
 */
//--------------------------------------------------------
bool Pico11::is_SetDefaults_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for SetDefaults command.
	/*----- PROTECTED REGION ID(Pico11::SetDefaultsStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Pico11::SetDefaultsStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Pico11::is_StartStreaming_allowed()
 *	Description : Execution allowed for StartStreaming attribute
 */
//--------------------------------------------------------
bool Pico11::is_StartStreaming_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for StartStreaming command.
	/*----- PROTECTED REGION ID(Pico11::StartStreamingStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Pico11::StartStreamingStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Pico11::is_StopStreaming_allowed()
 *	Description : Execution allowed for StopStreaming attribute
 */
//--------------------------------------------------------
bool Pico11::is_StopStreaming_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for StopStreaming command.
	/*----- PROTECTED REGION ID(Pico11::StopStreamingStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Pico11::StopStreamingStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Pico11::is_Update_allowed()
 *	Description : Execution allowed for Update attribute
 */
//--------------------------------------------------------
bool Pico11::is_Update_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Update command.
	/*----- PROTECTED REGION ID(Pico11::UpdateStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Pico11::UpdateStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Pico11::is_On_allowed()
 *	Description : Execution allowed for On attribute
 */
//--------------------------------------------------------
bool Pico11::is_On_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for On command.
	/*----- PROTECTED REGION ID(Pico11::OnStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Pico11::OnStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Pico11::is_Off_allowed()
 *	Description : Execution allowed for Off attribute
 */
//--------------------------------------------------------
bool Pico11::is_Off_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Off command.
	/*----- PROTECTED REGION ID(Pico11::OffStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Pico11::OffStateAllowed
	return true;
}


/*----- PROTECTED REGION ID(Pico11::Pico11StateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	Pico11::Pico11StateAllowed.AdditionalMethods

}	//	End of namespace
