/*----- PROTECTED REGION ID(Pico11Class.h) ENABLED START -----*/
//=============================================================================
//
// file :        Pico11Class.h
//
// description : Include for the Pico11 root class.
//               This class is the singleton class for
//                the Pico11 device class.
//               It contains all properties and methods which the 
//               Pico11 requires only once e.g. the commands.
//
// project :     Pico11
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
// Pico11
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef Pico11Class_H
#define Pico11Class_H

#include <tango.h>
#include <Pico11.h>


/*----- PROTECTED REGION END -----*/	//	Pico11Class.h


namespace Pico11_ns
{
/*----- PROTECTED REGION ID(Pico11Class::classes for dynamic creation) ENABLED START -----*/


/*----- PROTECTED REGION END -----*/	//	Pico11Class::classes for dynamic creation

//=========================================
//	Define classes for attributes
//=========================================
//	Attribute chanAstream class definition
class chanAstreamAttrib: public Tango::Attr
{
public:
	chanAstreamAttrib():Attr("chanAstream",
			Tango::DEV_DOUBLE, Tango::READ) {};
	~chanAstreamAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<Pico11 *>(dev))->read_chanAstream(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<Pico11 *>(dev))->is_chanAstream_allowed(ty);}
};

//	Attribute DevChoose class definition
class DevChooseAttrib: public Tango::Attr
{
public:
	DevChooseAttrib():Attr("DevChoose",
			Tango::DEV_DOUBLE, Tango::WRITE) {};
	~DevChooseAttrib() {};
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<Pico11 *>(dev))->write_DevChoose(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<Pico11 *>(dev))->is_DevChoose_allowed(ty);}
};

//	Attribute DevCh class definition
class DevChAttrib: public Tango::Attr
{
public:
	DevChAttrib():Attr("DevCh",
			Tango::DEV_STRING, Tango::READ) {};
	~DevChAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<Pico11 *>(dev))->read_DevCh(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<Pico11 *>(dev))->is_DevCh_allowed(ty);}
};

//	Attribute chanA class definition
class chanAAttrib: public Tango::SpectrumAttr
{
public:
	chanAAttrib():SpectrumAttr("chanA",
			Tango::DEV_DOUBLE, Tango::READ, 10000) {};
	~chanAAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<Pico11 *>(dev))->read_chanA(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<Pico11 *>(dev))->is_chanA_allowed(ty);}
};

//	Attribute chanB class definition
class chanBAttrib: public Tango::SpectrumAttr
{
public:
	chanBAttrib():SpectrumAttr("chanB",
			Tango::DEV_DOUBLE, Tango::READ, 10000) {};
	~chanBAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<Pico11 *>(dev))->read_chanB(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<Pico11 *>(dev))->is_chanB_allowed(ty);}
};

//	Attribute chanC class definition
class chanCAttrib: public Tango::SpectrumAttr
{
public:
	chanCAttrib():SpectrumAttr("chanC",
			Tango::DEV_DOUBLE, Tango::READ, 10000) {};
	~chanCAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<Pico11 *>(dev))->read_chanC(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<Pico11 *>(dev))->is_chanC_allowed(ty);}
};

//	Attribute chanD class definition
class chanDAttrib: public Tango::SpectrumAttr
{
public:
	chanDAttrib():SpectrumAttr("chanD",
			Tango::DEV_DOUBLE, Tango::READ, 10000) {};
	~chanDAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<Pico11 *>(dev))->read_chanD(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<Pico11 *>(dev))->is_chanD_allowed(ty);}
};


//=========================================
//	Define classes for commands
//=========================================
//	Command SetDefaults class definition
class SetDefaultsClass : public Tango::Command
{
public:
	SetDefaultsClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	SetDefaultsClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~SetDefaultsClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<Pico11 *>(dev))->is_SetDefaults_allowed(any);}
};

//	Command StartStreaming class definition
class StartStreamingClass : public Tango::Command
{
public:
	StartStreamingClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	StartStreamingClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~StartStreamingClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<Pico11 *>(dev))->is_StartStreaming_allowed(any);}
};

//	Command StopStreaming class definition
class StopStreamingClass : public Tango::Command
{
public:
	StopStreamingClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	StopStreamingClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~StopStreamingClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<Pico11 *>(dev))->is_StopStreaming_allowed(any);}
};

//	Command Update class definition
class UpdateClass : public Tango::Command
{
public:
	UpdateClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	UpdateClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~UpdateClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<Pico11 *>(dev))->is_Update_allowed(any);}
};

//	Command On class definition
class OnClass : public Tango::Command
{
public:
	OnClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	OnClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~OnClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<Pico11 *>(dev))->is_On_allowed(any);}
};

//	Command Off class definition
class OffClass : public Tango::Command
{
public:
	OffClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	OffClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~OffClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<Pico11 *>(dev))->is_Off_allowed(any);}
};


/**
 *	The Pico11Class singleton definition
 */

#ifdef _TG_WINDOWS_
class __declspec(dllexport)  Pico11Class : public Tango::DeviceClass
#else
class Pico11Class : public Tango::DeviceClass
#endif
{
	/*----- PROTECTED REGION ID(Pico11Class::Additionnal DServer data members) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	Pico11Class::Additionnal DServer data members

	public:
		//	write class properties data members
		Tango::DbData	cl_prop;
		Tango::DbData	cl_def_prop;
		Tango::DbData	dev_def_prop;
	
		//	Method prototypes
		static Pico11Class *init(const char *);
		static Pico11Class *instance();
		~Pico11Class();
		Tango::DbDatum	get_class_property(string &);
		Tango::DbDatum	get_default_device_property(string &);
		Tango::DbDatum	get_default_class_property(string &);
	
	protected:
		Pico11Class(string &);
		static Pico11Class *_instance;
		void command_factory();
		void attribute_factory(vector<Tango::Attr *> &);
		void pipe_factory();
		void write_class_property();
		void set_default_property();
		void get_class_property();
		string get_cvstag();
		string get_cvsroot();
	
	private:
		void device_factory(const Tango::DevVarStringArray *);
		void create_static_attribute_list(vector<Tango::Attr *> &);
		void erase_dynamic_attributes(const Tango::DevVarStringArray *,vector<Tango::Attr *> &);
		vector<string>	defaultAttList;
		Tango::Attr *get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname);
};

}	//	End of namespace

#endif   //	Pico11_H
